export const AppRoutes = {
  HOME: "/",
  BLOCKS: "/blocks",
  DOCS: {
    INTRO: "/docs",
    INSTALLATION: "/docs/installation",
    THEMING: "/docs/theming",
  },
  COMPONENTS: {
    ALERT: "/component/alert",
    ALERT_DIALOG: "/component/alert-dialog",
    BADGE: "/component/badge",
    BREADCRUMB: "/component/breadcrumb",
    BUTTON: "/component/button",
    CARD: "/component/card",
    CHECKBOX: "/component/checkbox",
    CHART: "/component/chart",
    DIALOG: "/component/dialog",
    SHEET: "/component/sheet",
    INPUT: "/component/input",
    LABEL: "/component/label",
    SWITCH: "/component/switch",
    SKELETON: "/component/skeleton",
    TEXTAREA: "/component/textarea",
    TOAST: "/component/toast",
    TOGGLE: "/component/toggle",
    TOOLTIP: "/component/tooltip",
    CALENDAR: "/component/calendar",
    DRAWER: "/component/drawer",
    SELECT: "/component/select",
    TABLE: "/component/table",
    CAROUSEL: "/component/carousel",
  },
} as const;
