export const AppRoutes = {
  HOME: "/",
  EXAMPLES: "/examples",
  DOCS: {
    INTRO: "/docs",
    INSTALLATION: "/docs/installation",
    INSTALLATION_VITE: "/docs/installation/vite",
    INSTALLATION_ASTRO: "/docs/installation/astro",
    THEMING: "/docs/theming",
    DARK_MODE: "/docs/dark",
  },
  COMPONENTS: {
    ACCORDION: "/component/accordion",
    ALERT: "/component/alert",
    ALERT_DIALOG: "/component/alert-dialog",
    ASPECT_RATIO: "/component/aspect-ratio",
    AVATAR: "/component/avatar",
    BADGE: "/component/badge",
    BREADCRUMB: "/component/breadcrumb",
    BUTTON: "/component/button",
    CALENDAR: "/component/calendar",
    CARD: "/component/card",
    CAROUSEL: "/component/carousel",
    CHART: "/component/chart",
    CHECKBOX: "/component/checkbox",
    COLLAPSIBLE: "/component/collapsible",
    COMMAND: "/component/command",
    DIALOG: "/component/dialog",
    DRAWER: "/component/drawer",
    INPUT: "/component/input",
    INPUT_OTP: "/component/input_otp",
    LABEL: "/component/label",
    POPOVER: "/component/popover",
    PROGRESS: "/component/progress",
    RESIZABLE: "/component/resizable",
    SELECT: "/component/select",
    SEPARATOR: "/component/separator",
    SHEET: "/component/sheet",
    SKELETON: "/component/skeleton",
    SWITCH: "/component/switch",
    TABLE: "/component/table",
    TABS: "/component/tabs",
    TEXTAREA: "/component/textarea",
    TOAST: "/component/toast",
    TOGGLE: "/component/toggle",
    TOOLTIP: "/component/tooltip",
  },
} as const;
